---
laptops:
  hosts:
    localhost:
      ansible_connection: local

pythondevel:
  hosts:
    localhost:
      ansible_connection: local

i3wm:
  hosts:
    localhost:
      ansible_connection: local
