---
- hosts: all
  become: yes
  tasks:
    - name: Install basic packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ inventory.group_vars.all.packages }}"

- name: Install packages based on group
  hosts: laptop
  become: yes
  tasks:
    - name: Install packages for the group
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ inventory.group_vars.laptop.packages }}"


- name: Install packages based on group
  hosts: python-devel
  become: yes
  tasks:
    - name: Install packages for the group
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ inventory.group_vars.pythondevel.packages }}"

- name: Create folders for development hosts
  hosts: pythondevel
  tasks:
    - name: Create repos dir
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/repos"
        state: directory
        mode: '0755'
    - name: Clone repos
      git:
        repo: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/repos/"
        clone: yes
        update: yes
      loop: "{{ inventory.group_vars.pythondevelrepos }}"

- name: Create folders for development hosts
  hosts: i3wm
  tasks:
    - name: Create repos dir
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/repos"
        state: directory
        mode: '0755'
    - name: Clone repos
      git:
        repo: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/repos/"
        clone: yes
        update: yes
      loop: "{{ inventory.group_vars.i3wm.repos }}"


- name: Configure shell environment
  hosts: all
  tasks:
    - name: Install Oh My ZSH
      become: yes
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
